apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "httpbin.fullname" . }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - {{ include "httpbin.fullname" . }}.{{ .Values.subdomain }}
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - {{ include "httpbin.fullname" . }}.{{ .Values.subdomain }}
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: secret-cert
      mode: ISTIO_MUTUAL
